[package]
name = "fgbdump"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
crossterm = "0.29.0"
flatgeobuf = "6.0.1"
geozero = "0.15.1"
ratatui = "0.30.0"
tokio = {version = "1.48.0", features = ["full"]}
